import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { MyContext } from "@/context";
import { SessionProvider } from "next-auth/react";

const poppins = Poppins({ subsets: ["latin"], weight:['400'] });

export const metadata: Metadata = {
  title: "TNV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SessionProvider>
          <MyContext>
            <div >
              <main >
                <Toaster />
                {children}
              </main>
            </div>
          </MyContext>
        </SessionProvider>
      </body>
    </html>
  );
}
