import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/custom/Header/Header";
import Footer from "@/components/custom/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="flex flex-col min-h-screen">
        <Header/>
        <div className="flex grow">
          <Toaster />
          {children}
        </div>
        <Footer/>
      </div>
  );
}
